apiVersion: app.matej.nl/v1alpha1
kind: Website
metadata:
  labels:
    app.kubernetes.io/name: website-operator
    app.kubernetes.io/managed-by: kustomize
  name: website-sample
spec:
  replicas: 2
  message: "Hello world"
  # TODO(user): Add fields here
